name: Build for amd64 Architecture
on:
  workflow_dispatch:

  push:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout to target repo
        uses: actions/checkout@v2
        with:
          repository: talhaHavadar/governor.badgerd.nl
          ref: rust
          token: ${{ secrets.PAT_TOKEN }}
      - name: Install dependencies
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          cargo install cargo-deb
          sudo apt install tree -y
      - name: Build the application
        run: |
          cargo deb
      - name: List the output
        run: |
          tree ./target/debian
          tar -czvf build-artifacts.tar.gz ./target
      - name: Upload the artifacts
        id: upload-artifacts
        uses: actions/upload-artifact@v4
        with:
          path: build-artifacts.tar.gz
          retention-days: 1
      - name: Put run id to pr
        run: |
          echo 'run id ${{ github.run_id }}'
